name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Package deployment artifact
        run: |
          zip -r pipeline-artifact.zip dags include docs README.md

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-artifact
          path: pipeline-artifact.zip